import { StyleSheet } from "react-native";

import { colors, shadow } from "../constants/theme";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.cream,
  },
  topBar: {
    paddingHorizontal: 20,
    paddingBottom: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  topBarSubtitle: {
    fontSize: 12,
    fontWeight: "500",
    color: colors.muted,
    marginBottom: 4,
  },
  topBarTitle: {
    fontSize: 22,
    fontWeight: "700",
    letterSpacing: -0.55,
    color: colors.ink,
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.mist,
    alignItems: "center",
    justifyContent: "center",
  },
  conversation: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
    gap: 10,
  },
  bubbleText: {
    fontSize: 14.5,
    lineHeight: 21,
    color: colors.ink,
  },
  bubbleSubtext: {
    color: colors.muted,
  },
  thinkingBubble: {
    alignSelf: "flex-start",
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 18,
    borderBottomLeftRadius: 6,
    backgroundColor: colors.paper,
    borderWidth: 1,
    borderColor: colors.line2,
  },
  quickChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginLeft: 4,
  },
  confirmCardWrap: {
    marginTop: 4,
  },
  confirmActions: {
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
  },
  confirmNote: {
    fontSize: 11.5,
    color: colors.muted2,
    textAlign: "center",
    marginTop: 2,
  },
  failCard: {
    backgroundColor: colors.paper,
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.indigo100,
    borderLeftWidth: 3,
    borderLeftColor: colors.indigo,
  },
  failHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  failHeaderText: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.indigo,
  },
  failBody: {
    fontSize: 13.5,
    lineHeight: 20,
    color: colors.ink2,
    marginBottom: 12,
  },
  failChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  systemText: {
    color: colors.muted2,
    fontSize: 12,
  },
  inputBarWrap: {
    paddingHorizontal: 14,
    paddingTop: 10,
    backgroundColor: colors.cream,
  },
  inputBar: {
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: colors.line2,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  inputText: {
    flex: 1,
    fontSize: 14.5,
    color: colors.ink,
    padding: 0,
  },
  inputSubmit: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  doneCenter: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    gap: 24,
  },
  successOrb: {
    width: 120,
    height: 120,
    alignItems: "center",
    justifyContent: "center",
  },
  successOrbOuter: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 60,
    backgroundColor: colors.indigo50,
  },
  successOrbMid: {
    position: "absolute",
    top: 16,
    left: 16,
    right: 16,
    bottom: 16,
    borderRadius: 44,
    backgroundColor: colors.indigo100,
  },
  successOrbInner: {
    position: "absolute",
    top: 32,
    left: 32,
    right: 32,
    bottom: 32,
    borderRadius: 28,
    backgroundColor: colors.indigo,
    alignItems: "center",
    justifyContent: "center",
    ...shadow.sm,
  },
  doneTitle: {
    fontSize: 24,
    fontWeight: "700",
    letterSpacing: -0.72,
    marginBottom: 6,
    color: colors.ink,
  },
  doneSubtitle: {
    fontSize: 14,
    color: colors.muted,
    textAlign: "center",
    lineHeight: 21,
  },
  doneCardWrap: {
    width: "100%",
    paddingHorizontal: 4,
  },
  doneFooter: {
    paddingHorizontal: 20,
    paddingBottom: 36,
    paddingTop: 16,
    gap: 9,
  },
});
